# Generated by Django 4.2 on 2023-05-23 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_rename_sarf_yanit_sarfmalzememodel_sarf_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='hijyenmodel',
            name='gorevli_kisi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijyen_gorevli_kisi', to='blog.gorevlimodel'),
        ),
        migrations.AddField(
            model_name='tasimamodel',
            name='gorevli_kisi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasima_gorevli_kisi', to='blog.gorevlimodel'),
        ),
    ]
